from __future__ import annotations

from dataclasses import dataclass


# Layer C fallback dictionary: easy to extend over time.
# Compiled from HKJC GraphQL API data (live odds + results, 2026-05-17).
# Competition names follow HKJC standard Traditional Chinese (Cantonese) naming.
_COMPETITION_ZH_MAP: dict[str, str] = {
    "Argentine Division 1": "阿根廷甲組聯賽",
    "Asian Champions League 2": "亞冠盃2",
    "Australian Division 1": "澳洲職業聯賽",
    "Belgian Division 1": "比利時甲組聯賽",
    "Brazilian Division 1": "巴西甲組聯賽",
    "Chilean Division 1": "智利甲組聯賽",
    "Cup Competition": "盃賽",
    "Dutch Division 1": "荷蘭甲組聯賽",
    "Dutch Division 2": "荷蘭乙組聯賽",
    "Eng Premier": "英格蘭超級聯賽",
    "English Championship": "英格蘭冠軍聯賽",
    "English Premier League": "英格蘭超級聯賽",
    "Eng League 1": "英格蘭甲組聯賽",
    "Eng League 2": "英格蘭乙組聯賽",
    "FA Cup": "英格蘭足總盃",
    "Finnish Division 1": "芬蘭超級聯賽",
    "French Division 2": "法國乙組聯賽",
    "German Division 1": "德國甲組聯賽",
    "Italian Division 1": "意大利甲組聯賽",
    "J1 100Y Vision League": "日職百年構想聯賽",
    "J2 J3 100Y Vision League": "日乙日丙百年構想聯賽",
    "Korean Division 1": "南韓職業聯賽",
    "Korean Division 2": "南韓乙組聯賽",
    "Mexican Division 1": "墨西哥甲組聯賽",
    "Mexican Premier": "墨西哥超級聯賽",
    "Norwegian Division 1": "挪威超級聯賽",
    "Portuguese Premier": "葡萄牙超級聯賽",
    "Saudi Pro League": "沙特職業聯賽",
    "Scottish Premier": "蘇格蘭超級聯賽",
    "Spanish Division 1": "西班牙甲組聯賽",
    "Spanish Division 2": "西班牙乙組聯賽",
    "Swedish Division 1": "瑞典超級聯賽",
    "UAE Pro League": "阿聯酋職業聯賽",
    "US Major League": "美國職業聯賽",
    "Uruguayan Division 1": "烏拉圭甲組聯賽",
    "Women Argentine Division 1": "女子阿根廷甲組聯賽",
    "Women Australian Division 1": "女子澳洲職業聯賽",
    "Women Brazilian Division 1": "女子巴西甲組聯賽",
    "Women Brazilian Paulista League": "女子巴西聖保羅省聯賽",
    "Women Dutch Cup": "女子荷蘭盃",
    "Women Eng Premier": "女子英格蘭超級聯賽",
    "Women French Division 1": "女子法國甲組聯賽",
    "Women Japanese Division 1": "女子日本職業聯賽",
    "Women Korean Division 1": "女子南韓職業聯賽",
    "Women Mexican Premier": "女子墨西哥超級聯賽",
    "Women Norwegian Division 1": "女子挪威超級聯賽",
    "Women Russian Premier": "女子俄羅斯超級聯賽",
    "Women Spanish Cup": "女子西班牙盃",
    "Women Swedish Cup": "女子瑞典盃",
    "Women Swedish Division 1": "女子瑞典超級聯賽",
    "Women US Football League": "女子美國職業聯賽",
}

# Team name mapping: English → Traditional Chinese (HKJC standard Cantonese).
# Covers EPL, EFL, La Liga, Serie A, Bundesliga, Ligue 1, Eredivisie, Primeira Liga,
# Scottish Premiership, K League, J League, A-League, MLS, Saudi Pro League, UAE League,
# Brazilian, Argentine, Chilean, Mexican, Uruguayan leagues, and major women's leagues.
# Source: HKJC GraphQL API live data + historical data (2026-05-17).
_TEAM_ZH_MAP: dict[str, str] = {
    "1. FC Magdeburg": "馬格德堡",
    "1. FC Nurnberg": "紐倫堡",
    "AC Milan": "AC米蘭",
    "AC Oulu": "AC奧盧",
    "AFC Bournemouth": "般尼茅夫",
    "AFC Wimbledon": "AFC溫布頓",
    "AZ Alkmaar": "阿爾克馬爾",
    "Accrington Stanley": "阿克寧頓",
    "Adelaide Utd": "阿德萊德聯",
    "Ajax": "阿積士",
    "Al Ahli Jeddah": "吉達艾阿里",
    "Al Ain": "艾阿恩",
    "Al Hilal": "希拉爾",
    "Al Ittihad": "伊蒂哈德",
    "Al Nassr": "艾納斯",
    "Alaves": "艾拉維斯",
    "Almere City": "阿梅爾城",
    "Almeria": "艾美利亞",
    "Anderlecht": "安德列治",
    "Angers": "昂熱",
    "Antwerp": "安特衛普",
    "Arsenal": "阿仙奴",
    "Arsenal Women": "阿仙奴女足",
    "Aston Villa": "阿士東維拉",
    "Aston Villa Women": "阿士東維拉女足",
    "Atalanta": "阿特蘭大",
    "Athletic Bilbao": "畢爾包",
    "Atlanta United": "阿特蘭大聯",
    "Atlanta Utd": "阿特蘭大聯",
    "Atletico Madrid": "馬德里體育會",
    "Atletico Madrid Women": "馬德里體育會女足",
    "Atletico Mineiro": "明尼路",
    "Augsburg": "奧格斯堡",
    "Austin FC": "奧斯汀FC",
    "Auxerre": "歐塞爾",
    "Barcelona": "巴塞隆拿",
    "Barcelona Women": "巴塞隆拿女足",
    "Barnsley": "班士利",
    "Barrow": "巴羅",
    "Bayern Munich": "拜仁慕尼黑",
    "Bayern": "拜仁慕尼黑",
    "Bayer Leverkusen": "利華古遜",
    "Benfica": "賓菲加",
    "Blackburn Rovers": "布力般流浪",
    "Blackpool": "黑池",
    "Bodo Glimt": "波杜基林特",
    "Bologna": "博洛尼亞",
    "Bolton": "保頓",
    "Borussia Dortmund": "多蒙特",
    "Borussia Monchengladbach": "慕遜加柏",
    "Bournemouth": "般尼茅夫",
    "Bradford": "巴拉福特",
    "Bradford City": "巴拉福特",
    "Braga": "布拉加",
    "Brentford": "賓福特",
    "Brest": "比斯特",
    "Brighton": "白禮頓",
    "Brighton & Hove Albion": "白禮頓",
    "Brighton Women": "白禮頓女足",
    "Bristol City": "布里斯托城",
    "Bristol Rovers": "布里斯托流浪",
    "Burnley": "般尼",
    "Burton Albion": "保頓艾爾賓",
    "CF Montreal": "CF蒙特利爾",
    "Cadiz": "卡迪斯",
    "Cagliari": "卡利亞里",
    "Cardiff City": "卡迪夫城",
    "Carlisle United": "卡素爾",
    "Celtic": "些路迪",
    "Celta Vigo": "切爾達",
    "Cerezo Osaka": "大阪櫻花",
    "Charleroi": "查內爾",
    "Charlton Athletic": "查爾頓",
    "Chelsea": "車路士",
    "Chelsea Women": "車路士女足",
    "Cheltenham Town": "車頓咸",
    "Chesterfield": "車士打菲特",
    "Chicago Fire": "芝加哥火燄",
    "Chicago Fire FC": "芝加哥火燄",
    "Club Brugge": "布魯日",
    "Colchester United": "高車士打",
    "Cologne": "科隆",
    "Colorado Rapids": "科羅拉多急流",
    "Columbus Crew": "哥倫布機員",
    "Corinthians": "哥連泰斯",
    "Coventry City": "高雲地利",
    "Crawley Town": "卡維尼",
    "Crewe Alexandra": "克魯",
    "Crystal Palace": "水晶宮",
    "DC United": "華盛頓聯隊",
    "Darmstadt": "達斯泰特",
    "Derby County": "打比郡",
    "Dinamo Zagreb": "薩格勒布戴拿模",
    "Doncaster Rovers": "唐卡士打",
    "Dortmund": "多蒙特",
    "Dundee": "登地",
    "Dundee Utd": "登地聯",
    "Eintracht Frankfurt": "法蘭克福",
    "Eintracht Braunschweig": "布倫瑞克",
    "Empoli": "安玻里",
    "Espanyol": "愛斯賓奴",
    "Everton": "愛華頓",
    "Everton Women": "愛華頓女足",
    "Exeter City": "艾斯特城",
    "FC Cincinnati": "FC辛辛那提",
    "FC Dallas": "FC達拉斯",
    "FC Koln": "科隆",
    "FC Seoul": "FC首爾",
    "FC Tokyo": "FC東京",
    "Feyenoord": "飛燕諾",
    "Fiorentina": "費倫天拿",
    "Flamengo": "法林明高",
    "Fleetwood Town": "費列活特",
    "Fluminense": "富明尼斯",
    "Forest Green Rovers": "格林森林流浪",
    "Fortuna Dusseldorf": "杜斯多夫",
    "Frankfurt": "法蘭克福",
    "Freiburg": "弗賴堡",
    "Fulham": "富咸",
    "Gamba Osaka": "大阪飛腳",
    "Genoa": "熱拿亞",
    "Getafe": "基達菲",
    "Gil Vicente": "基維辛迪",
    "Gillingham": "基寧咸",
    "Girona": "基羅納",
    "Gremio": "甘美奧",
    "Greuther Furth": "格雷特霍夫",
    "Grimsby": "甘士比",
    "Grimsby Town": "甘士比",
    "Guadalajara": "瓜達拉哈拉",
    "HSV": "漢堡",
    "Hamburg": "漢堡",
    "Hamburger SV": "漢堡",
    "Hannover 96": "漢諾威",
    "Harrogate Town": "夏洛治",
    "Hearts": "赫斯",
    "Heerenveen": "海倫芬",
    "Heidenheim": "海登咸",
    "Hellas Verona": "維羅納",
    "Hertha Berlin": "哈化柏林",
    "Hibernian": "喜伯年",
    "Hoffenheim": "賀芬咸",
    "Houston Dynamo": "侯斯頓戴拿模",
    "Huddersfield Town": "哈特斯菲",
    "Huesca": "侯爾斯卡",
    "Hull City": "侯城",
    "Inter": "國際米蘭",
    "Inter Miami": "國際邁亞密",
    "Inter Miami CF": "國際邁亞密",
    "Inter Milan": "國際米蘭",
    "Ipswich": "葉士域治",
    "Ipswich Town": "葉士域治",
    "Juventus": "祖雲達斯",
    "Karlsruher SC": "卡爾斯魯厄",
    "Kashima Antlers": "鹿島鹿角",
    "Kawasaki Frontale": "川崎前鋒",
    "Kilmarnock": "基爾馬諾克",
    "LA Galaxy": "洛杉磯銀河",
    "LAFC": "洛杉磯FC",
    "Las Palmas": "拉斯彭馬斯",
    "Lazio": "拉素",
    "Le Havre": "勒哈弗爾",
    "Lecce": "萊切",
    "Leeds": "列斯聯",
    "Leeds United": "列斯聯",
    "Leganes": "雷加利斯",
    "Leicester": "李斯特城",
    "Leicester City": "李斯特城",
    "Leicester Women": "李斯特城女足",
    "Lens": "朗斯",
    "Leverkusen": "利華古遜",
    "Leyton Orient": "奧連特",
    "Lille": "里爾",
    "Lincoln City": "林肯城",
    "Liverpool": "利物浦",
    "Liverpool Women": "利物浦女足",
    "Los Angeles FC": "洛杉磯FC",
    "Luton Town": "盧頓",
    "Lyon": "里昂",
    "MK Dons": "米爾頓凱恩斯",
    "Mainz": "緬恩斯",
    "Malaga": "馬拉加",
    "Mallorca": "馬略卡",
    "Man City": "曼城",
    "Man Utd": "曼聯",
    "Manchester City": "曼城",
    "Manchester City Women": "曼城女足",
    "Manchester United": "曼聯",
    "Manchester Utd": "曼聯",
    "Manchester Utd Women": "曼聯女足",
    "Mansfield Town": "曼斯菲",
    "Marseille": "馬賽",
    "Middlesbrough": "米杜士堡",
    "Milan": "AC米蘭",
    "Millwall": "米禾爾",
    "Minnesota United": "明尼蘇達聯",
    "Mito Hollyhock": "水戶蜀葵",
    "Molde": "莫迪",
    "Monaco": "摩納哥",
    "Monchengladbach": "慕遜加柏",
    "Montpellier": "蒙彼利埃",
    "Monza": "蒙沙",
    "Morecambe": "摩甘比",
    "Motherwell": "馬瑟韋爾",
    "Nantes": "南特",
    "Napoli": "拿玻里",
    "Nashville SC": "拿舒維爾",
    "New England Revolution": "新英倫革命",
    "New York City": "紐約城",
    "New York Red Bulls": "紐約紅牛",
    "Newcastle": "紐卡素",
    "Newcastle United": "紐卡素",
    "Newport County": "新港郡",
    "Nice": "尼斯",
    "Norwich": "諾域治",
    "Norwich City": "諾域治",
    "Nott'm Forest": "諾定咸森林",
    "Nottingham Forest": "諾定咸森林",
    "Notts County": "諾士郡",
    "Olympique Marseille": "馬賽",
    "Orlando City": "奧蘭多城",
    "Osasuna": "奧沙辛拿",
    "Oxford United": "牛津聯",
    "PSG": "巴黎聖日耳門",
    "PSV": "燕豪芬",
    "PSV Eindhoven": "燕豪芬",
    "Palmeiras": "彭美拉斯",
    "Paris Saint-Germain": "巴黎聖日耳門",
    "Parma": "帕爾馬",
    "Philadelphia Union": "費城聯",
    "Plymouth Argyle": "普利茅夫",
    "Pohang Steelers": "浦項制鐵",
    "Port Vale": "維爾港",
    "Portland Timbers": "波特蘭伐木者",
    "Porto": "波圖",
    "Portsmouth": "樸茨茅夫",
    "Preston North End": "普雷斯頓",
    "QPR": "昆士柏流浪",
    "Queens Park Rangers": "昆士柏流浪",
    "RB Leipzig": "RB萊比錫",
    "Rangers": "格拉斯哥流浪",
    "Rayo Vallecano": "華歷簡奴",
    "Reading": "雷丁",
    "Real Betis": "貝迪斯",
    "Real Madrid": "皇家馬德里",
    "Real Salt Lake": "皇家鹽湖城",
    "Real Sociedad": "皇家蘇斯達",
    "Red Star Belgrade": "貝爾格萊德紅星",
    "Reims": "蘭斯",
    "Rennes": "雷恩",
    "River Plate": "河床",
    "Roma": "羅馬",
    "Ross County": "羅斯郡",
    "Rotherham United": "洛達咸",
    "SC Paderborn 07": "柏達邦",
    "SV Elversberg": "艾華斯堡",
    "Saint-Etienne": "聖伊天",
    "Salford City": "沙福特城",
    "San Diego FC": "聖地亞哥FC",
    "San Jose Earthquakes": "聖荷西地震",
    "Sanfrecce Hiroshima": "廣島三箭",
    "Santander": "桑坦德",
    "Sao Paulo": "聖保羅",
    "Schalke 04": "史浩克04",
    "Seattle Sounders": "西雅圖海灣者",
    "Sevilla": "西維爾",
    "Shakhtar Donetsk": "薩克達",
    "Sheffield United": "錫菲聯",
    "Sheffield Utd": "錫菲聯",
    "Sheffield Wed": "錫周三",
    "Sheffield Wednesday": "錫周三",
    "Shrewsbury Town": "梳士貝利",
    "Southampton": "修咸頓",
    "Sporting": "士砵亭",
    "Sporting CP": "士砵亭",
    "Sporting Kansas City": "肯薩斯體育會",
    "St. Etienne": "聖伊天",
    "St. Johnstone": "聖莊士東",
    "St. Louis CITY SC": "聖路易斯城",
    "St. Louis City": "聖路易斯城",
    "St. Mirren": "聖美倫",
    "St. Pauli": "聖保利",
    "Stade Brestois": "比斯特",
    "Stade Rennais": "雷恩",
    "Stevenage": "史提芬納治",
    "Stockport County": "史托港",
    "Stoke City": "史篤城",
    "Strasbourg": "史特拉斯堡",
    "Stuttgart": "史特加",
    "Sunderland": "新特蘭",
    "Sutton United": "瑟頓聯",
    "Swansea City": "史雲斯",
    "Swindon Town": "史雲頓",
    "Sydney FC": "FC悉尼",
    "Torino": "拖連奴",
    "Toronto FC": "多倫多FC",
    "Tottenham": "熱刺",
    "Tottenham Hotspur": "熱刺",
    "Tottenham Women": "熱刺女足",
    "Toulouse": "圖盧茲",
    "Tranmere Rovers": "燦美爾",
    "Twente": "川迪",
    "Udinese": "烏甸尼斯",
    "Ulsan HD": "蔚山HD",
    "Union Berlin": "柏林聯",
    "Universidad Catolica": "天主教大學",
    "Urawa Reds": "浦和紅鑽",
    "Valencia": "華倫西亞",
    "Valladolid": "華拉度列",
    "Vancouver Whitecaps": "溫哥華白帽",
    "Venezia": "威尼斯",
    "Verona": "維羅納",
    "Villarreal": "維拉利爾",
    "Vissel Kobe": "神戶勝利船",
    "Walsall": "華素爾",
    "Watford": "屈福特",
    "Werder Bremen": "雲達不來梅",
    "West Brom": "西布朗",
    "West Bromwich Albion": "西布朗",
    "West Ham": "韋斯咸",
    "West Ham United": "韋斯咸",
    "West Ham Women": "韋斯咸女足",
    "Wigan Athletic": "韋根",
    "Willem II": "威廉二世",
    "Wolfsburg": "禾夫斯堡",
    "Wolverhampton": "狼隊",
    "Wolverhampton Wanderers": "狼隊",
    "Wolves": "狼隊",
    "Wycombe Wanderers": "韋甘比",
    "Yokohama F.Marinos": "橫濱水手",
}

_MARKET_LABEL_ZH_MAP: dict[str, str] = {
    "ah_ft": "讓球",
    "hdc": "讓球",
    "edc": "讓球",
}

_SIDE_LABEL_ZH_MAP: dict[str, str] = {
    "home": "主",
    "away": "客",
    "h": "主",
    "a": "客",
    "主": "主",
    "客": "客",
}


@dataclass(frozen=True)
class MatchDisplay:
    competition: str
    home_team: str
    away_team: str


def resolve_competition_name(raw_name: str, lang: str = "zh-HK", payload_name_zh: str | None = None) -> str:
    """Resolve competition to HKJC-style Chinese display with safe fallback."""
    if lang.lower() != "zh-hk":
        return _safe_text(payload_name_zh) or _safe_text(raw_name)

    zh_payload = _safe_text(payload_name_zh)
    if zh_payload:
        return zh_payload

    key = _safe_text(raw_name)
    if not key:
        return ""
    return _COMPETITION_ZH_MAP.get(key, key)


def resolve_team_name(raw_name: str, lang: str = "zh-HK", payload_name_zh: str | None = None) -> str:
    """Resolve team name to HKJC-style Chinese display with safe fallback."""
    if lang.lower() != "zh-hk":
        return _safe_text(payload_name_zh) or _safe_text(raw_name)

    zh_payload = _safe_text(payload_name_zh)
    if zh_payload:
        return zh_payload

    key = _safe_text(raw_name)
    if not key:
        return ""
    return _TEAM_ZH_MAP.get(key, key)


def resolve_market_label(
    *,
    market_id: str | None = None,
    market_type: str | None = None,
    predicted_side: str | None = None,
    lang: str = "zh-HK",
) -> str:
    """Resolve market + side wording in HKJC-style Chinese."""
    side_label = _SIDE_LABEL_ZH_MAP.get(_safe_text(predicted_side).lower(), _safe_text(predicted_side) or "主")
    if lang.lower() != "zh-hk":
        return f"AH {side_label}".strip()

    market_key = _safe_text(market_id).lower() or _safe_text(market_type).lower()
    market_label = _MARKET_LABEL_ZH_MAP.get(market_key, "讓球")
    return f"{market_label}{side_label}"


def resolve_match_display(
    home_team: str,
    away_team: str,
    competition: str,
    *,
    lang: str = "zh-HK",
    home_team_zh: str | None = None,
    away_team_zh: str | None = None,
    competition_zh: str | None = None,
) -> MatchDisplay:
    """Resolve competition/home/away display names with layered fallback."""
    resolved_competition = resolve_competition_name(competition, lang=lang, payload_name_zh=competition_zh)
    resolved_home = resolve_team_name(home_team, lang=lang, payload_name_zh=home_team_zh)
    resolved_away = resolve_team_name(away_team, lang=lang, payload_name_zh=away_team_zh)

    return MatchDisplay(
        competition=resolved_competition or _safe_text(competition),
        home_team=resolved_home or _safe_text(home_team),
        away_team=resolved_away or _safe_text(away_team),
    )


def _safe_text(value: str | None) -> str:
    if value is None:
        return ""
    text = str(value).strip()
    if text.lower() in {"nan", "none", "null", "na", "n/a"}:
        return ""
    return text
